config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :categories
  resources :brands
  resources :cars
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :cars
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image
  has_one :rent
  belongs_to :category
  belongs_to :brand

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :cars
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :car

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
      if @brand.save
        redirect_to brands_path
      else
        render :new
      end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
      if @brand.update(brand_params)
        redirect_to brands_path
      else
        render :edit
      end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    redirect_to brands_path
  end

  private
    def brand_params
      params.require(:brand).permit(:brandName)
    end



end

app/controllers/cars_controller.rb
class CarsController < ApplicationController


    def index
      @cars = Car.all
    end

    def show
      @car = Car.find(params[:id])
    end

    def new
      @car = Car.new
    end

    def create
      @car = Car.new(car_params)
        if @car.save
          @car.image.attach(params[:car][:image])
          redirect_to cars_path
        else
          render :new
        end
    end

    def edit
      @car = Car.find(params[:id])
    end

    def update
      @car = Car.find(params[:id])
        if @car.update(car_params)
          redirect_to cars_path
        else
          render :edit
        end
    end

    def destroy
      @car = Car.find(params[:id])
      @car.destroy
      redirect_to cars_path
    end

    private
      def car_params
        params.require(:car).permit(:name, :description, :price, :category_id, :brand_id, :image, :stock)
      end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categorys = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to categories_path
      else
        render :new
      end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
      if @category.update(category_params)
        redirect_to categories_path
      else
        render :edit
      end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:categoryName)
    end


end

app/controllers/rents_controller.rb
class RentsController < ApplicationController

  require 'action_view'
  include ActionView::Helpers::DateHelper

    def index
      @rents = Rent.all
    end

    def show
      @rent = Rent.find(params[:id])
    end

    def new
      @rent = Rent.new
    end

    def create
      @rent = Rent.new(rent_params)
        if @rent.save
          redirect_to rents_path
        else
          render :new
        end
    end

    def edit
      @rent = Rent.find(params[:id])
    end

    def update
      @rent = Rent.find(params[:id])
        if @rent.update(rent_params)
          redirect_to rents_path
        else
          render :edit
        end
    end

    def destroy
      @rent = Rent.find(params[:id])
      @rent.destroy
      redirect_to rents_path
    end

    private
      def rent_params
        params.require(:rent).permit(:tenantName, :car_id, :pickup, :dropoff, :duration, :fine, :cost)
      end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/brands/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Edit brand</title>
  </head>
  <body>
    <%= form_for @brand do |brand| %>
    <div>
      <%= brand.label :brandName %>
      <%= brand.text_field :brandName %>
    </div>
    <div>
      <%= brand.submit %>
    </div>
    <% end %>
  </body>
</html>

app/views/brands/index.html.erb
<ul>
  <li> <%= link_to "Car List", cars_path %></li>
  <li> <%= link_to "Brand List", brands_path %></li>
  <li> <%= link_to "Category List", categories_path %></li>
  <li> <%= link_to "Rental List", rents_path %></li>

</ul>

    <p id=”notice”><%= notice %></p>

    <h1>brand List</h1>

    <table>
      <thead>
        <th>Name</th>
        <th>Aksi</th>
      </thead>
      <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.brandName %></td>
        <td>
          <%= link_to "Edit", edit_brand_path(brand) %>
        </td>

      </tr>
      <% end %>
      <%= link_to "Tambah brand", new_brand_path %>

    <table>

app/views/brands/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tambah brand</title>
  </head>
  <body>
    <%= form_for @brand do |brand| %>
    <div>
      <%= brand.label :brandName %>
      <%= brand.text_field :brandName %>
    </div>
    <div>
      <%= brand.submit %>
    </div>
    <% end %>
  </body>
</html>

app/views/cars/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tambah car</title>
  </head>
  <body>


      <%= form_for @car do |car| %>
      <div>
        <%= car.label :name %>
        <%= car.text_field :name %>
      </div>
      <div>
        <%= car.label :brand_id %>
        <%= collection_select( :car, :brand_id, Brand.all , :id, :brandName, {}, { :multiple => false }  ) %>
      </div>
      <div>
        <%= car.label :category_id %>
        <%= collection_select( :car, :category_id, Category.all , :id, :categoryName, {}, { :multiple => false }  ) %>
      </div>
      <div>
        <%= car.label :description %>
        <%= car.text_field :description %>
      </div>
      <div>
        <%= car.label :price %>
        <%= car.text_field :price %>
      </div>
      <div>
        <%= car.label :image %>
        <%= image_tag(@car.image) %>
      </div>
      <div>
        <%= car.label :stock %>
        <%= car.text_field :stock %>
      </div>
      <div>
        <%= car.submit %>
      </div>
      <% end %>


  </body>
</html>

app/views/cars/index.html.erb
<ul>
  <li> <%= link_to "Car List", cars_path %></li>
  <li> <%= link_to "Brand List", brands_path %></li>
  <li> <%= link_to "Category List", categories_path %></li>
  <li> <%= link_to "Rental List", rents_path %></li>

</ul>

    <p id=”notice”><%= notice %></p>

    <h1>car List</h1>

    <table width="1000px">
      <thead>
        <th>Name</th>
        <th>Brand</th>
        <th>Category</th>
        <th>description</th>
        <th>Stock</th>
        <th>Price</th>
        <th>image</th>
        <th>Action</th>

      </thead>
      <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.brand.brandName %></td>
        <td><%= car.category.categoryName %></td>
        <td><%= car.description %></td>
        <td><%= car.stock %></td>
        <td><%= car.price %></td>
        <td><%= image_tag(car.image) %></td>
        <td><%= link_to "Edit", edit_car_path(car) %>
        <%= link_to "Delete", car, method: :delete, data: { confirm: "Yakin mau di delete ?"} %></td>

      </tr>
      <% end %>
      <%= link_to "Tambah car", new_car_path %>

    <table>

app/views/cars/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tambah car</title>
  </head>
  <body>
    <%= form_for @car do |car| %>
    <div>
      <%= car.label :name %>
      <%= car.text_field :name %>
    </div>
    <div>
      <%= car.label :brand_id %>
      <%= collection_select( :car, :brand_id, Brand.all , :id, :brandName, {}, { :multiple => false }  ) %>
    </div>
    <div>
      <%= car.label :category_id %>
      <%= collection_select( :car, :category_id, Category.all , :id, :categoryName, {}, { :multiple => false }  ) %>
    </div>
    <div>
      <%= car.label :description %>
      <%= car.text_field :description %>
    </div>
    <div>
      <%= car.label :price %>
      <%= car.text_field :price %>
    </div>
    <div>
      <%= car.label :image %>
      <%= car.file_field :image %>
    </div>
    <div>
      <%= car.label :stock %>
      <%= car.text_field :stock %>
    </div>
    <div>
      <%= car.submit %>
    </div>
    <% end %>
  </body>
</html>

app/views/categories/edit.html.erb
    <%= form_for @category do |category| %>
    <div>
      <%= category.label :categoryName %>
      <%= category.text_field :categoryName %>
    </div>
    <div>
      <%= category.submit %>
    </div>
    <% end %>

app/views/categories/index.html.erb
<ul>
  <li> <%= link_to "Car List", cars_path %></li>
  <li> <%= link_to "Brand List", brands_path %></li>
  <li> <%= link_to "Category List", categories_path %></li>
  <li> <%= link_to "Rental List", rents_path %></li>

</ul>

    <p id=”notice”><%= notice %></p>

    <h1>category List</h1>

    <table>
      <thead>
        <th>Name</th>
        <th>Aksi</th>
      </thead>
      <% @categorys.each do |category| %>
      <tr>
        <td><%= category.categoryName %></td>
        <td>
          <%= link_to "Edit", edit_category_path(category) %>
        </td>

      </tr>
      <% end %>
      <%= link_to "Tambah category", new_category_path %>

    <table>

app/views/categories/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tambah category</title>
  </head>
  <body>
    <%= form_for @category do |category| %>
    <div>
      <%= category.label :categoryName %>
      <%= category.text_field :categoryName %>
    </div>
    <div>
      <%= category.submit %>
    </div>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalMobil</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rents/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tambah rent</title>
  </head>
  <body>
    <%= form_for @rent do |rent| %>
    <div>
      <%= rent.label :tenantName %>
      <%= rent.text_field :tenantName %>
    </div>
    <div>
      <%= rent.label :car_id %>
      <%= collection_select( :rent, :car_id, Car.all , :id, :name, {}, { :multiple => false }  ) %>
    </div>
    <div>
      <%= rent.label :pickup %>
      <%= rent.date_select :pickup %>
    </div>
    <div>
      <%= rent.label :dropoff %>
      <%= rent.date_select :dropoff %>
    </div>
    <div>
      <%= rent.label :duration %>
      <%= rent.text_field :duration %>
    </div>

    <div>
      <%= rent.submit %>
    </div>
    <% end %>
  </body>
</html>

app/views/rents/index.html.erb
<ul>
  <li> <%= link_to "Car List", cars_path %></li>
  <li> <%= link_to "Brand List", brands_path %></li>
  <li> <%= link_to "Category List", categories_path %></li>
  <li> <%= link_to "Rental List", rents_path %></li>

</ul>

    <p id=”notice”><%= notice %></p>

    <h1>rent List</h1>

    <table>
      <thead>
        <th>Tenant's Name</th>
        <th>Car's Name</th>
        <th>Pick Up</th>
        <th>Duration</th>
        <th>Drop Off</th>
        <th>Denda</th>
        <th>Biaya Dikenakan</th>
        <th>Aksi</th>
      </thead>
      <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.tenantName %></td>
        <td><%= rent.car.name %></td>
        <td><%= rent.pickup %></td>
        <td><%= rent.duration %> Day</td>
        <td><%= rent.dropoff %></td>
        <td>Rp.
          <%
          start_date = Date.parse "#{rent.pickup}"
          end_date =  Date.parse "#{rent.dropoff}"
          tes = (end_date.to_date - start_date.to_date).to_i
          %>
          <% if tes > 1 %>
            <%= @denda = (((end_date.to_date - start_date.to_date).to_i) - 1) * 50000 %>
          <% else %>
            <%= 0 %>
          <% end %>


        </td>
        <td>Rp. <%= (rent.duration * rent.car.price) + @denda %></td>

        <td>
          <%= link_to "Edit", edit_rent_path(rent) %>
          <%= link_to "Delete", rent, method: :delete, data: { confirm: "Yakin mau di delete ?"} %>
        </td>

      </tr>
      <% end %>
      <%= link_to "Tambah rent", new_rent_path %>

    <table>

app/views/rents/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tambah rent</title>
  </head>
  <body>
    <%= form_for @rent do |rent| %>
    <div>
      <%= rent.label :tenantName %>
      <%= rent.text_field :tenantName %>
    </div>
    <div>
      <%= rent.label :car_id %>
      <%= collection_select( :rent, :car_id, Car.all , :id, :name, {}, { :multiple => false }  ) %>
    </div>
    <div>
      <%= rent.label :pickup %>
      <%= rent.date_select :pickup %>
    </div>
    <div>
      <%= rent.label :dropoff %>
      <%= rent.date_select :dropoff %>
    </div>
    <div>
      <%= rent.label :duration %>
      <%= rent.text_field :duration %>
    </div>

    <div>
      <%= rent.submit %>
    </div>
    <% end %>
  </body>
</html>